version: '3'
services:
  jenkins-integration:
    image: guhtiagosilva/jenkins-integration:11.0
    container_name: jenkins-integration
    ports:
      - "80:8082"
    environment:
      - DB_DATASOURCE_URL=jdbc:postgresql://postgres:5432/booksdb
      - DB_USERNAME=gustavo
      - DB_PASSWORD=1234567
      - PORT=8082
      - ZIPKIN_SPANS_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - postgres
      - zipkin
      - prometheus
      - grafana
    networks:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: gustavo
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: booksdb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - postgres
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - postgres
    volumes:
      - ./monitoring/grafana/datasources/:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - postgres
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - postgres
  jenkins-agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: jenkins-agent
    networks:
      - postgres
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmFHfuKhC4EFkUJkppbJlwQChkxWMrzXH5x8nP4pD+gM8IFNnqG2AEwoEPI1bvuV4EbKIm8KwTZ167IplUcLXtHTZTKaRZJzkopF4S5KxfkA/uD5YqT6VPedQUXHfeSUdDU/8Ny6IVqqJU0fMVRAQifvVUaLEcISXsexYE3b4P1RxBj6ly8jA7VJrPbyaHqtcsj2IaCbPkymFrazFPVWufYucAS78EoERMd7u/qqX1BcAl6qLjY5rQdVISLTRc+brxXCKajjwsG6QDNMm7sjkXrH07CHHnYJfzJ1+S64PNJSWCh7FAUQHmdVBTZagqzD1hirRyMzwxnYDGKfvxW6+W+T6PDixMS38FZNFM0opd59soIBj4zKLFQpPKA7nO9q0f+4IpeRDIeyff94DON1tobQjfJtNQIZETLT0EwFz1qvGY29hlHA4ZsCxsEjmK11pH/PtTOmvcmTYv5ldsVcqE7KSr3bbezPgC61k2R705y9A+l8lLFYZ0XN0P7oejOQE= gustavo@gustavo-G5-5590
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  jenkins: