version: '3'
services:
  jenkins-integration:
    image: guhtiagosilva/jenkins-integration:3.0
    container_name: jenkins-integration
    ports:
      - 80:8082
    environment:
      - DB_DATASOURCE_URL=jdbc:postgresql://postgres:5432/booksdb
      - DB_USERNAME=gustavo
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=8082
    depends_on:
      - postgres
    networks:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: gustavo
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: booksdb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins:/var/jenkins_home
    networks:
      - postgres
  jenkins-agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: jenkins-agent
    networks:
      - postgres
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${YOUR_PUBLIC_SSH_KEY}
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  jenkins: