version: '3'
services:
  jenkins-integration:
    image: guhtiagosilva/jenkins-integration:1.0
    container_name: jenkins-integration
    ports:
      - 80:8080
    environment:
      - DB_DATASOURCE_URL=jdbc:postgresql://postgres:5432/booksdb
      - DB_USERNAME=gustavo
      - DB_PASSWORD=1234567
    depends_on:
      - postgres
    networks:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: gustavo
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: booksdb
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: