scrape_configs:
  - job_name: 'metrics-collector'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'jenkins-integration:8082' ]
        labels:
          application: 'Spring Boot Application'